### ISSUE TITLE
goxdcr. restarting without any solution to stop or clear it

### ISSUE THREAD

**Issue by PaulB2Code** [couchbase/goxdcr#8] opened 2021-04-14 21:15 UTC
Dear All, 

Please find what happens  in Enterprise Edition 7.0.0 build 3739 ‧ IPv4 ‧ encrypted   © 2020 Couchbase, Inc.

During a creation of new scope in server receiving the xdcr.

Service 'goxdcr' exited with status 2. Restarting. Messages:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f21a0]

goroutine 1 [running]:
github.com/couchbase/goxdcr/metadata.(*VBTasksMapType).LoadFromMappingsShaMap(0xc0000ea1a8, 0xc000237470, 0x4f, 0xc000368080)
/home/couchbase/jenkins/workspace/couchbase-server-unix/goproj/src/github.com/couchbase/goxdcr/metadata/backfill_replication.go:277 +0x100
github.com/couchbase/goxdcr/metadata_svc.(*BackfillReplicationService).initCacheFromMetaKV(0xc0002e2f20, 0x0, 0x0)
/home/couchbase/jenkins/workspace/couchbase-server-unix/goproj/src/github.com/couchbase/goxdcr/metadata_svc/backfill_repl_service.go:175 +0x984
github.com/couchbase/goxdcr/metadata_svc.NewBackfillReplicationService(0xeb8da0, 0xc000237f50, 0xedb780, 0xc000238a20, 0xc0000aac70, 0xee8400, 0xc00023a710, 0xede9c0, 0xc00024e750, 0xec3e40, ...)
/home/couchbase/jenkins/workspace/couchbase-server-unix/goproj/src/github.com/couchbase/goxdcr/metadata_svc/backfill_repl_service.go:81 +0x1ab
main.main()
goproj/src/github.com/couchbase/goxdcr/main/main.go:174 +0xff2

**Comment by nelio2k** [comment] 2021-04-14 23:57
This can be marked as a duplicate of https://issues.couchbase.com/browse/MB-45601
The fix will include this

**Closed as completed** 2021-04-15 05:36 UTC
